exports.Route = function (ID_CART, CART, NART, CATEGORY, BRAND, MODEL, COLOR, SIZE, PRICEA, PRICEB, PRICEC, PRICED, PRICEE, PRICEF, IMAGE_EXT, PROV, FAB, PROMO, PMES) {
  this.method = ID_CART
  this.route = CART
  this.controller = NART
  this.category = CATEGORY
  this.brand = BRAND
  this.model = MODEL
  this.color = COLOR
  this.size = SIZE
  this.priceA = PRICEA
  this.priceB = PRICEB
  this.priceC = PRICEC
  this.priceD = PRICED
  this.priceE = PRICEE
  this.priceF = PRICEF
  this.imageExt = IMAGE_EXT
  this.prov = PROV
  this.fab = FAB
  this.promo = PROMO
  this.nart = NART
  this.pmes = PMES
}
